source "https://supermarket.getchef.com"

cookbook 'libffi', :path => 'cookbooks/libffi'
cookbook 'ruby', :path => 'cookbooks/ruby'
cookbook 'jenkins-setup', :path => 'cookbooks/jenkins-setup'

metadata
