# NOTE: Latest version of vagrant has some weird issues when you halt or reload
# Delete .vagrant/machines/default/virtualbox/synced_folders to fix

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Centos 7 box
    config.vm.box = 'https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box'

    # Jenkins
    config.vm.network 'forwarded_port', guest: 8080, host: 9080

    config.omnibus.chef_version = :latest
    config.berkshelf.enabled = true

    config.vm.provision 'chef_solo' do |chef|
        chef.roles_path = 'roles'
        chef.add_role('ruby')
        chef.add_role('java')
        chef.add_role('jenkins')
    end
end