VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = 'https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box'

    config.omnibus.chef_version = :latest
    config.berkshelf.enabled = true

    config.vm.provision 'chef_solo' do |chef|
        chef.roles_path = 'roles'
        chef.add_role('ruby')
        chef.add_role('java')
    end
end