# NOTE: Latest version of vagrant has some weird issues when you halt or reload
# Delete .vagrant/machines/default/virtualbox/synced_folders to fix

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Centos 7 box
    config.vm.box = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box'

    # Jenkins
    config.vm.network 'forwarded_port', guest: 9090, host: 9000

    config.omnibus.chef_version = :latest
    config.berkshelf.enabled = true

    config.vm.provision 'chef_solo' do |chef|
        chef.roles_path = 'roles'
        chef.add_role('ruby')
        chef.add_role('java')
        chef.add_role('jenkins')
    end
end